services:
  - type: shopify server for uploads
    name: fullstack-app
    env: node

    # Build and install the frontend (Vite) and backend (Express)
    buildCommand: |
      cd src && npm install && npm run build
      cd ../server && npm install

    startCommand: node server/server.js

    # The root directory for the backend service (this will be where your Express server is located)
    rootDir: server

    # Optional: Set environment variables for your app (e.g., MongoDB URI, JWT secret)
    envVars:
      - key: NODE_VERSION
        value: ^3.0.1
      - key: MONGODB_URI
        value: mongodb+srv://nickparodi:admin007@shirtshop.zarz3a.mongodb.net/?retryWrites=true&w=majority&appName=ShirtShop
      - key: JWT_SECRET
        value: 1cdd4a66e3d4fa51350d56b97431fe4ecd2e7dc386e28492872de719ef857474
